"""Create invite_tokens table

Revision ID: 006
Revises: 005
Create Date: 2026-09-23

Stores one-time invite tokens that allow specific email addresses to
join an organization. Generated by ORG_ADMINs, consumed on registration.
Tokens expire after 48 hours and are single-use.

To apply:    alembic upgrade head
To roll back: alembic downgrade -1
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = "007"
down_revision = "006"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create the invite_tokens table."""
    op.create_table(
        "invite_tokens",

        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            nullable=False,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "organization_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("organizations.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "email",
            sa.String(320),
            nullable=False,
            comment="Email address this invite was sent to",
        ),
        sa.Column(
            "token",
            sa.String(128),
            nullable=False,
            comment="URL-safe random invite token",
        ),
        sa.Column(
            "role",
            sa.String(50),
            nullable=False,
            server_default="EMPLOYEE",
            comment="Role the invitee will receive",
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "is_used",
            sa.Boolean(),
            nullable=False,
            server_default="false",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
    )

    op.create_unique_constraint("uq_invite_tokens_token", "invite_tokens", ["token"])
    op.create_index("ix_invite_tokens_token", "invite_tokens", ["token"], unique=True)
    op.create_index("ix_invite_tokens_email", "invite_tokens", ["email"])
    op.create_index("ix_invite_tokens_organization_id", "invite_tokens", ["organization_id"])


def downgrade() -> None:
    """Drop the invite_tokens table."""
    op.drop_index("ix_invite_tokens_organization_id", table_name="invite_tokens")
    op.drop_index("ix_invite_tokens_email", table_name="invite_tokens")
    op.drop_index("ix_invite_tokens_token", table_name="invite_tokens")
    op.drop_table("invite_tokens")
