"""Create invite_tokens table

Revision ID: 007
Revises: 006
Create Date: 2026-09-23

Stores one-time invite tokens that allow specific email addresses to
join an organization. Generated by ORG_ADMINs, consumed on registration.
Tokens expire after 48 hours and are single-use.

To apply:    alembic upgrade head
To roll back: alembic downgrade -1
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = "009"
down_revision: Union[str, None] = "008"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "invite_tokens",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            nullable=False,
            server_default=sa.text("gen_random_uuid()"),
            comment="Unique record identifier",
        ),
        sa.Column(
            "organization_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("organizations.id", ondelete="CASCADE"),
            nullable=False,
            comment="Which organization the invitee is being added to",
        ),
        sa.Column(
            "email",
            sa.String(320),
            nullable=False,
            comment="The email address this invite was sent to — must match on registration",
        ),
        sa.Column(
            "token",
            sa.String(128),
            nullable=False,
            unique=True,
            comment="URL-safe random token sent to the invitee",
        ),
        sa.Column(
            "role",
            sa.String(50),
            nullable=False,
            server_default="EMPLOYEE",
            comment="The role the invitee will receive upon registration",
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="When this invite expires (typically now + 48 hours)",
        ),
        sa.Column(
            "is_used",
            sa.Boolean(),
            nullable=False,
            server_default="false",
            comment="True once the invitee has registered — prevents reuse",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
            comment="When the invite was generated",
        ),
    )
    op.create_index("ix_invite_tokens_organization_id", "invite_tokens", ["organization_id"])
    op.create_index("ix_invite_tokens_email", "invite_tokens", ["email"])
    op.create_index("ix_invite_tokens_token", "invite_tokens", ["token"], unique=True)


def downgrade() -> None:
    op.drop_index("ix_invite_tokens_token", table_name="invite_tokens")
    op.drop_index("ix_invite_tokens_email", table_name="invite_tokens")
    op.drop_index("ix_invite_tokens_organization_id", table_name="invite_tokens")
    op.drop_table("invite_tokens")
