"""create email verification tokens table

Revision ID: 4bd4f3668cde
Revises: 007
Create Date: 2026-09-23 11:37:58.939500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4bd4f3668cde'
down_revision: Union[str, None] = '007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verification_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='The user who needs to verify their email'),
    sa.Column('token', sa.String(length=255), nullable=False, comment='The actual verification token sent to the user'),
    sa.Column('is_used', sa.Boolean(), nullable=False, comment='True if the token was already used'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='When this token expires'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_verification_tokens_token'), 'email_verification_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_email_verification_tokens_user_id'), 'email_verification_tokens', ['user_id'], unique=False)
    op.alter_column('invite_tokens', 'id',
               existing_type=sa.UUID(),
               comment='Unique record identifier',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('invite_tokens', 'organization_id',
               existing_type=sa.UUID(),
               comment='Which organization the invitee is being added to',
               existing_nullable=False)
    op.alter_column('invite_tokens', 'email',
               existing_type=sa.VARCHAR(length=320),
               comment='The email address this invite was sent to — must match on registration',
               existing_comment='Email address this invite was sent to',
               existing_nullable=False)
    op.alter_column('invite_tokens', 'token',
               existing_type=sa.VARCHAR(length=128),
               comment='URL-safe random token sent to the invitee',
               existing_comment='URL-safe random invite token',
               existing_nullable=False)
    op.alter_column('invite_tokens', 'role',
               existing_type=sa.VARCHAR(length=50),
               comment='The role the invitee will receive upon registration',
               existing_comment='Role the invitee will receive',
               existing_nullable=False,
               existing_server_default=sa.text("'EMPLOYEE'::character varying"))
    op.alter_column('invite_tokens', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When this invite expires (typically now + 48 hours)',
               existing_nullable=False)
    op.alter_column('invite_tokens', 'is_used',
               existing_type=sa.BOOLEAN(),
               comment='True once the invitee has registered — prevents reuse',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('invite_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When the invite was generated',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('uq_invite_tokens_token', 'invite_tokens', type_='unique')
    op.alter_column('knowledge_base_documents', 'organization_id',
               existing_type=sa.UUID(),
               comment='Organization this document belongs to — NEVER query without this filter',
               existing_comment='Organization this document belongs to',
               existing_nullable=False)
    op.alter_column('knowledge_base_documents', 'title',
               existing_type=sa.VARCHAR(length=500),
               comment='Document title, shown in the KB list view',
               existing_comment='Document title',
               existing_nullable=False)
    op.alter_column('knowledge_base_documents', 'category',
               existing_type=sa.VARCHAR(length=150),
               comment="Optional category tag, e.g. 'HR Policies', 'Onboarding', 'SOPs'",
               existing_comment="Category tag, e.g. 'HR', 'SOPs', 'Policies'",
               existing_nullable=True)
    op.alter_column('knowledge_base_documents', 'created_by',
               existing_type=sa.UUID(),
               comment='The admin user who created this document',
               existing_comment='Admin user who created this document',
               existing_nullable=True)
    op.alter_column('knowledge_base_documents', 'is_published',
               existing_type=sa.BOOLEAN(),
               comment='False = draft (visible to admins only). True = visible to all members.',
               existing_comment='True = visible to all members. False = draft (admin-only).',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('knowledge_base_documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When the document was created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('knowledge_base_documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When the document was last edited',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_kb_documents_category', table_name='knowledge_base_documents')
    op.drop_index('ix_kb_documents_org_published', table_name='knowledge_base_documents')
    op.drop_index('ix_kb_documents_organization_id', table_name='knowledge_base_documents')
    op.create_index(op.f('ix_knowledge_base_documents_category'), 'knowledge_base_documents', ['category'], unique=False)
    op.create_index(op.f('ix_knowledge_base_documents_organization_id'), 'knowledge_base_documents', ['organization_id'], unique=False)
    op.alter_column('organizations', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment="Display name of the organization, e.g. 'Acme Corp'",
               existing_comment="Display name, e.g. 'Acme Corporation'",
               existing_nullable=False)
    op.alter_column('organizations', 'slug',
               existing_type=sa.VARCHAR(length=100),
               comment="URL-safe unique identifier, e.g. 'acme-corp'. Auto-generated from name.",
               existing_comment="URL-safe unique identifier, e.g. 'acme-corporation'",
               existing_nullable=False)
    op.alter_column('organizations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When this organization was registered',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('organizations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When this organization was last updated',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('uq_organizations_slug', 'organizations', type_='unique')
    op.alter_column('password_reset_tokens', 'id',
               existing_type=sa.UUID(),
               comment='Unique record identifier',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('password_reset_tokens', 'user_id',
               existing_type=sa.UUID(),
               comment='The user requesting a password reset',
               existing_nullable=False)
    op.alter_column('password_reset_tokens', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When this token expires (typically now + 1 hour)',
               existing_nullable=False)
    op.alter_column('password_reset_tokens', 'is_used',
               existing_type=sa.BOOLEAN(),
               comment='True once the token has been used — prevents replay attacks',
               existing_comment='Marks token as consumed — prevents replay attacks',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('password_reset_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When the reset was requested',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('uq_password_reset_tokens_token', 'password_reset_tokens', type_='unique')
    op.alter_column('refresh_tokens', 'id',
               existing_type=sa.UUID(),
               comment='Unique record identifier',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('refresh_tokens', 'user_id',
               existing_type=sa.UUID(),
               comment='The user this token belongs to',
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'token',
               existing_type=sa.VARCHAR(length=256),
               comment='The opaque refresh token string (128-char hex, 512-bit entropy)',
               existing_comment='Opaque random refresh token (128-char hex)',
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When this refresh token expires',
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When this token was created (= login time)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('uq_refresh_tokens_token', 'refresh_tokens', type_='unique')
    op.alter_column('users', 'organization_id',
               existing_type=sa.UUID(),
               comment='Organization this user belongs to (multi-tenant isolation key)',
               existing_comment='Organization this user belongs to',
               existing_nullable=True)
    op.alter_column('users', 'department_id',
               existing_type=sa.UUID(),
               comment='Department this user belongs to (optional)',
               existing_comment='Department this user belongs to',
               existing_nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment='Full name of the user (spec field: full_name)',
               existing_comment='Full name',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=320),
               comment='Email address — unique across the entire system',
               existing_comment='Email address — unique',
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               comment="bcrypt hash of the user's password — NEVER store plain text",
               existing_comment='bcrypt hash — NEVER plain text',
               existing_nullable=False)
    op.alter_column('users', 'is_email_verified',
               existing_type=sa.BOOLEAN(),
               comment="Whether the user's email address has been verified",
               existing_comment="Whether the user's email has been verified",
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('SUPER_ADMIN', 'ORG_ADMIN', 'SUPERVISOR', 'DEPARTMENT_AGENT', 'FIELD_WORKER', 'EMPLOYEE', name='userrole'),
               comment="User's role — controls what they can access",
               existing_comment='User role',
               existing_nullable=False,
               existing_server_default=sa.text("'EMPLOYEE'::userrole"))
    op.alter_column('users', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'INACTIVE', 'SUSPENDED', name='userstatus'),
               comment='Account status — only ACTIVE users can log in',
               existing_comment='Account status',
               existing_nullable=False,
               existing_server_default=sa.text("'ACTIVE'::userstatus"))
    op.alter_column('users', 'job_title',
               existing_type=sa.VARCHAR(length=150),
               comment="e.g. 'Senior Support Agent'",
               existing_nullable=True)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=30),
               comment='Phone number (international format recommended)',
               existing_nullable=True)
    op.alter_column('users', 'timezone',
               existing_type=sa.VARCHAR(length=60),
               comment="IANA timezone string, e.g. 'Asia/Karachi'",
               existing_nullable=True,
               existing_server_default=sa.text("'UTC'::character varying"))
    op.alter_column('users', 'profile_picture',
               existing_type=sa.VARCHAR(length=500),
               comment='URL to profile image (stored externally, e.g. S3)',
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When this user account was created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When this user account was last modified',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('uq_users_email', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_users_email', 'users', ['email'])
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When this user account was last modified',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When this user account was created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'profile_picture',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='URL to profile image (stored externally, e.g. S3)',
               existing_nullable=True)
    op.alter_column('users', 'timezone',
               existing_type=sa.VARCHAR(length=60),
               comment=None,
               existing_comment="IANA timezone string, e.g. 'Asia/Karachi'",
               existing_nullable=True,
               existing_server_default=sa.text("'UTC'::character varying"))
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='Phone number (international format recommended)',
               existing_nullable=True)
    op.alter_column('users', 'job_title',
               existing_type=sa.VARCHAR(length=150),
               comment=None,
               existing_comment="e.g. 'Senior Support Agent'",
               existing_nullable=True)
    op.alter_column('users', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'INACTIVE', 'SUSPENDED', name='userstatus'),
               comment='Account status',
               existing_comment='Account status — only ACTIVE users can log in',
               existing_nullable=False,
               existing_server_default=sa.text("'ACTIVE'::userstatus"))
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('SUPER_ADMIN', 'ORG_ADMIN', 'SUPERVISOR', 'DEPARTMENT_AGENT', 'FIELD_WORKER', 'EMPLOYEE', name='userrole'),
               comment='User role',
               existing_comment="User's role — controls what they can access",
               existing_nullable=False,
               existing_server_default=sa.text("'EMPLOYEE'::userrole"))
    op.alter_column('users', 'is_email_verified',
               existing_type=sa.BOOLEAN(),
               comment="Whether the user's email has been verified",
               existing_comment="Whether the user's email address has been verified",
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               comment='bcrypt hash — NEVER plain text',
               existing_comment="bcrypt hash of the user's password — NEVER store plain text",
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=320),
               comment='Email address — unique',
               existing_comment='Email address — unique across the entire system',
               existing_nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment='Full name',
               existing_comment='Full name of the user (spec field: full_name)',
               existing_nullable=False)
    op.alter_column('users', 'department_id',
               existing_type=sa.UUID(),
               comment='Department this user belongs to',
               existing_comment='Department this user belongs to (optional)',
               existing_nullable=True)
    op.alter_column('users', 'organization_id',
               existing_type=sa.UUID(),
               comment='Organization this user belongs to',
               existing_comment='Organization this user belongs to (multi-tenant isolation key)',
               existing_nullable=True)
    op.create_unique_constraint('uq_refresh_tokens_token', 'refresh_tokens', ['token'])
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When this token was created (= login time)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('refresh_tokens', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When this refresh token expires',
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'token',
               existing_type=sa.VARCHAR(length=256),
               comment='Opaque random refresh token (128-char hex)',
               existing_comment='The opaque refresh token string (128-char hex, 512-bit entropy)',
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='The user this token belongs to',
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Unique record identifier',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.create_unique_constraint('uq_password_reset_tokens_token', 'password_reset_tokens', ['token'])
    op.alter_column('password_reset_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When the reset was requested',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('password_reset_tokens', 'is_used',
               existing_type=sa.BOOLEAN(),
               comment='Marks token as consumed — prevents replay attacks',
               existing_comment='True once the token has been used — prevents replay attacks',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('password_reset_tokens', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When this token expires (typically now + 1 hour)',
               existing_nullable=False)
    op.alter_column('password_reset_tokens', 'user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='The user requesting a password reset',
               existing_nullable=False)
    op.alter_column('password_reset_tokens', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Unique record identifier',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.create_unique_constraint('uq_organizations_slug', 'organizations', ['slug'])
    op.alter_column('organizations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When this organization was last updated',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('organizations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When this organization was registered',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('organizations', 'slug',
               existing_type=sa.VARCHAR(length=100),
               comment="URL-safe unique identifier, e.g. 'acme-corporation'",
               existing_comment="URL-safe unique identifier, e.g. 'acme-corp'. Auto-generated from name.",
               existing_nullable=False)
    op.alter_column('organizations', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment="Display name, e.g. 'Acme Corporation'",
               existing_comment="Display name of the organization, e.g. 'Acme Corp'",
               existing_nullable=False)
    op.drop_index(op.f('ix_knowledge_base_documents_organization_id'), table_name='knowledge_base_documents')
    op.drop_index(op.f('ix_knowledge_base_documents_category'), table_name='knowledge_base_documents')
    op.create_index('ix_kb_documents_organization_id', 'knowledge_base_documents', ['organization_id'], unique=False)
    op.create_index('ix_kb_documents_org_published', 'knowledge_base_documents', ['organization_id', 'is_published'], unique=False)
    op.create_index('ix_kb_documents_category', 'knowledge_base_documents', ['category'], unique=False)
    op.alter_column('knowledge_base_documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When the document was last edited',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('knowledge_base_documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When the document was created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('knowledge_base_documents', 'is_published',
               existing_type=sa.BOOLEAN(),
               comment='True = visible to all members. False = draft (admin-only).',
               existing_comment='False = draft (visible to admins only). True = visible to all members.',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('knowledge_base_documents', 'created_by',
               existing_type=sa.UUID(),
               comment='Admin user who created this document',
               existing_comment='The admin user who created this document',
               existing_nullable=True)
    op.alter_column('knowledge_base_documents', 'category',
               existing_type=sa.VARCHAR(length=150),
               comment="Category tag, e.g. 'HR', 'SOPs', 'Policies'",
               existing_comment="Optional category tag, e.g. 'HR Policies', 'Onboarding', 'SOPs'",
               existing_nullable=True)
    op.alter_column('knowledge_base_documents', 'title',
               existing_type=sa.VARCHAR(length=500),
               comment='Document title',
               existing_comment='Document title, shown in the KB list view',
               existing_nullable=False)
    op.alter_column('knowledge_base_documents', 'organization_id',
               existing_type=sa.UUID(),
               comment='Organization this document belongs to',
               existing_comment='Organization this document belongs to — NEVER query without this filter',
               existing_nullable=False)
    op.create_unique_constraint('uq_invite_tokens_token', 'invite_tokens', ['token'])
    op.alter_column('invite_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When the invite was generated',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('invite_tokens', 'is_used',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='True once the invitee has registered — prevents reuse',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('invite_tokens', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When this invite expires (typically now + 48 hours)',
               existing_nullable=False)
    op.alter_column('invite_tokens', 'role',
               existing_type=sa.VARCHAR(length=50),
               comment='Role the invitee will receive',
               existing_comment='The role the invitee will receive upon registration',
               existing_nullable=False,
               existing_server_default=sa.text("'EMPLOYEE'::character varying"))
    op.alter_column('invite_tokens', 'token',
               existing_type=sa.VARCHAR(length=128),
               comment='URL-safe random invite token',
               existing_comment='URL-safe random token sent to the invitee',
               existing_nullable=False)
    op.alter_column('invite_tokens', 'email',
               existing_type=sa.VARCHAR(length=320),
               comment='Email address this invite was sent to',
               existing_comment='The email address this invite was sent to — must match on registration',
               existing_nullable=False)
    op.alter_column('invite_tokens', 'organization_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Which organization the invitee is being added to',
               existing_nullable=False)
    op.alter_column('invite_tokens', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Unique record identifier',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.drop_index(op.f('ix_email_verification_tokens_user_id'), table_name='email_verification_tokens')
    op.drop_index(op.f('ix_email_verification_tokens_token'), table_name='email_verification_tokens')
    op.drop_table('email_verification_tokens')
    # ### end Alembic commands ###
